# Generated by Django 5.2.5 on 2025-09-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
