# Generated by Django 5.2.5 on 2025-09-15 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_available_copies_book_total_copies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
    ]
