# Generated by Django 5.2.5 on 2025-09-19 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_studentprofile_address_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.RemoveField(
            model_name='book',
            name='available_copies',
        ),
        migrations.RemoveField(
            model_name='book',
            name='total_copies',
        ),
    ]
