# Generated by Django 5.2.5 on 2025-09-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_book_total_copies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_copies',
        ),
    ]
